name: Node.js Environments CI

on:
  push:
    branches:
      - main

jobs:
  dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run calculator in dev
        run: node calculator.js add 1 2

  staging:
    runs-on: ubuntu-latest
    environment: staging
    needs: dev
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run calculator in staging
        run: node calculator.js add 1 2

  prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: staging
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run calculator in prod
        run: node calculator.js add 1 2 