name: Node.js Environments CI

on:
  push:
    branches:
      - main
      - dev
      - staging

jobs:
  dev:
    runs-on: ubuntu-latest
    environment: dev
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run testing of calculator
        run: npm run test
      
      - name : Deploying to vm
        run: |
          echo "Deploying to VM..."
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no azureuser@20.244.43.49 "mkdir -p /home/azureuser/calculator && cd /home/azureuser/calculator && git pull && npm install && pm2 restart calculator"


      

  staging:
    runs-on: ubuntu-latest
    environment: staging
    
    if: github.ref == 'refs/heads/staging'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run calculator in staging
        run: node calculator.js add 1 2

  prod:
    runs-on: ubuntu-latest
    environment: prod
    
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run calculator in prod
        run: node calculator.js add 1 2 